/* eslint-disable */

export default {
    defs: {
        grinning: '😀',
        smiley: '😃',
        smile: '😄',
        grin: '😁',
        laughing: '😆',
        satisfied: '😆',
        sweat_smile: '😅',
        gnar: '🤙',
        joy: '😂',
        blush: '😊',
        innocent: '😇',
        wink: '😉',
        relieved: '😌',
        heart_eyes: '😍',
        kissing_heart: '😘',
        kissing: '😗',
        kissing_smiling_eyes: '😙',
        kissing_closed_eyes: '😚',
        yum: '😋',
        stuck_out_tongue_winking_eye: '😜',
        stuck_out_tongue_closed_eyes: '😝',
        stuck_out_tongue: '😛',
        sunglasses: '😎',
        smirk: '😏',
        unamused: '😒',
        disappointed: '😞',
        pensive: '😔',
        worried: '😟',
        confused: '😕',
        persevere: '😣',
        confounded: '😖',
        tired_face: '😫',
        weary: '😩',
        angry: '😠',
        rage: '😡',
        pout: '😡',
        no_mouth: '😶',
        neutral_face: '😐',
        expressionless: '😑',
        hushed: '😯',
        frowning: '😞',
        anguished: '😧',
        open_mouth: '😮',
        astonished: '😲',
        dizzy_face: '😵',
        flushed: '😳',
        scream: '😱',
        fearful: '😨',
        cold_sweat: '😰',
        cry: '😢',
        disappointed_relieved: '😥',
        sob: '😭',
        sweat: '😓',
        sleepy: '😪',
        sleeping: '😴',
        mask: '😷',
        smiling_imp: '😈',
        smiley_cat: '😺',
        smile_cat: '😸',
        joy_cat: '😹',
        heart_eyes_cat: '😻',
        smirk_cat: '😼',
        kissing_cat: '😽',
        scream_cat: '🙀',
        crying_cat_face: '😿',
        pouting_cat: '😾',
        fist_raised: '✊',
        fist: '✊',
        v: '✌️',
        point_up: '☝️',
        hand: '✋',
        raised_hand: '✋',
        cat: '🐱',
        mouse: '🐭',
        cow: '🐮',
        monkey_face: '🐵',
        star: '⭐️',
        sparkles: '✨',
        zap: '⚡️',
        sunny: '☀️',
        cloud: '☁️',
        snowflake: '❄️',
        umbrella: '☔️',
        coffee: '☕️',
        airplane: '✈️',
        anchor: '⚓️',
        watch: '⌚️',
        phone: '☎️',
        telephone: '☎️',
        hourglass: '⌛️',
        email: '✉️',
        envelope: '✉️',
        scissors: '✂️',
        black_nib: '✒️',
        pencil2: '✏️',
        heart: '❤️',
        x: '❌',
        part_alternation_mark: '〽️',
        warning: '⚠️',
        recycle: '♻️',
        white_check_mark: '✅',
        negative_squared_cross_mark: '❎',
        information_source: 'ℹ️',
        heavy_plus_sign: '➕',
        heavy_minus_sign: '➖',
        heavy_division_sign: '➗',
        heavy_multiplication_x: '✖️',
        tm: '™️',
        copyright: '©️',
        registered: '®️',
        ballot_box_with_check: '☑️',
    },
    shortcuts: {
        angry: ['>:(', '>:-('],
        blush: [':")', ':-")', ':)', ':-)'],
        broken_heart: ['</3', '<\\3'],
        // :\ and :-\ not used because of conflict with markdown escaping
        confused: [':/', ':-/'], // twemoji shows question
        cry: [":'(", ":'-(", ':,(', ':,-('],
        heart: ['<3'],
        imp: [']:(', ']:-('],
        frowning: [':(', ':-('],
        innocent: ['o:)', 'O:)', 'o:-)', 'O:-)', '0:)', '0:-)'],
        joy: [":')", ":'-)", ':,)', ':,-)', ":'D", ":'-D", ':,D', ':,-D'],
        kissing: [':*', ':-*'],
        laughing: ['xD', 'x-)', 'X-)'],
        neutral_face: [':|', ':-|'],
        open_mouth: [':o', ':-o', ':O', ':-O'],
        rage: [':@', ':-@'],
        smile: [':D', ':-D'],
        smiling_imp: [']:)', ']:-)'],
        sob: [":,'(", ":,'-(", ';(', ';-('],
        stuck_out_tongue: [':P', ':-P'],
        sunglasses: ['8-)', 'B-)'],
        sweat: [',:(', ',:-('],
        sweat_smile: [',:)', ',:-)'],
        unamused: [':s', ':-S', ':z', ':-Z', ':$', ':-$'],
        wink: [';)', ';-)'],
    },
};
